### ISSUE TITLE
Incorrect table header and table body in the Project Table

### ISSUE THREAD

**Issue by ashwinkhode** [Venturh/maxwerpers-next#1]
In tablet view `(760px - 1024px)`, `fullstack` is coming under the `Year` column and `2021` is coming under the `Links` column

Screenshot:
![image](https://user-images.githubusercontent.com/53361996/138587255-3baa8aaa-c5ba-4759-9934-e4925d0d9144.png)

**Comment by Venturh** [comment]
Thanks for pointing it out and sorry that I didn't see your Issue earlier.
Should be fixed now 👍
